apiVersion: v1
kind: ConfigMap
metadata:
  name: logistic-config
data:
  DB_HOST: "logistic-db"
  DB_PORT: "5432"
  DB_NAME: "logistic_db"
  BROKER_HOST: "rabbitmq"
  CREATE_DELIVERY_TOPIC: "rpc_create_delivery"
---
apiVersion: v1
kind: Secret
metadata:
  name: logistic-secrets
type: Opaque
data:
  DB_USER: bG9naXN0aWM= # logistic base64 encoded
  DB_PASSWORD: cG9zdGdyZXM=  # postgres (base64 encoded)