# INGRESS
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ccp-ingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: "ccp-ingress-ip"
spec:
  rules:
  - http:
      paths:
      - path: /api/v1/users
        pathType: Prefix
        backend:
          service:
            name: users-api
            port:
              number: 80
      - path: /suppliers
        pathType: Prefix
        backend:
          service:
            name: suppliers-api
            port:
              number: 80
      - path: /api/v1/sales
        pathType: Prefix
        backend:
          service:
            name: sales-api
            port:
              number: 80
      - path: /logistic
        pathType: Prefix
        backend:
          service:
            name: logistic-api
            port:
              number: 80
      - path: /inventory
        pathType: Prefix
        backend:
          service:
            name: inventory-api
            port:
              number: 80
